/**
 * ElevenLabs Scribe supported languages (90+)
 * Source: https://elevenlabs.io/docs/capabilities/speech-to-text
 *
 * `code` maps directly to the language_code param in the Scribe API.
 * Empty string = auto-detect (Scribe will detect the language).
 */

export interface Language {
  code: string;
  label: string;
}

export const SCRIBE_LANGUAGES: Language[] = [
  // Auto-detect first
  { code: "",    label: "Auto-detect" },

  { code: "afr", label: "Afrikaans" },
  { code: "amh", label: "Amharic" },
  { code: "ara", label: "Arabic" },
  { code: "hye", label: "Armenian" },
  { code: "asm", label: "Assamese" },
  { code: "ast", label: "Asturian" },
  { code: "aze", label: "Azerbaijani" },
  { code: "bel", label: "Belarusian" },
  { code: "ben", label: "Bengali" },
  { code: "bos", label: "Bosnian" },
  { code: "bul", label: "Bulgarian" },
  { code: "mya", label: "Burmese" },
  { code: "yue", label: "Cantonese" },
  { code: "cat", label: "Catalan" },
  { code: "ceb", label: "Cebuano" },
  { code: "nya", label: "Chichewa" },
  { code: "hrv", label: "Croatian" },
  { code: "ces", label: "Czech" },
  { code: "dan", label: "Danish" },
  { code: "nld", label: "Dutch" },
  { code: "eng", label: "English" },
  { code: "est", label: "Estonian" },
  { code: "fil", label: "Filipino" },
  { code: "fin", label: "Finnish" },
  { code: "fra", label: "French" },
  { code: "ful", label: "Fulah" },
  { code: "glg", label: "Galician" },
  { code: "lug", label: "Ganda" },
  { code: "kat", label: "Georgian" },
  { code: "deu", label: "German" },
  { code: "ell", label: "Greek" },
  { code: "guj", label: "Gujarati" },
  { code: "hau", label: "Hausa" },
  { code: "heb", label: "Hebrew" },
  { code: "hin", label: "Hindi" },
  { code: "hun", label: "Hungarian" },
  { code: "isl", label: "Icelandic" },
  { code: "ibo", label: "Igbo" },
  { code: "ind", label: "Indonesian" },
  { code: "gle", label: "Irish" },
  { code: "ita", label: "Italian" },
  { code: "jpn", label: "Japanese" },
  { code: "jav", label: "Javanese" },
  { code: "kea", label: "Kabuverdianu" },
  { code: "kan", label: "Kannada" },
  { code: "kaz", label: "Kazakh" },
  { code: "khm", label: "Khmer" },
  { code: "kor", label: "Korean" },
  { code: "kur", label: "Kurdish" },
  { code: "kir", label: "Kyrgyz" },
  { code: "lao", label: "Lao" },
  { code: "lav", label: "Latvian" },
  { code: "lin", label: "Lingala" },
  { code: "lit", label: "Lithuanian" },
  { code: "luo", label: "Luo" },
  { code: "ltz", label: "Luxembourgish" },
  { code: "mkd", label: "Macedonian" },
  { code: "msa", label: "Malay" },
  { code: "mal", label: "Malayalam" },
  { code: "mlt", label: "Maltese" },
  { code: "zho", label: "Mandarin Chinese" },
  { code: "mri", label: "Māori" },
  { code: "mar", label: "Marathi" },
  { code: "mon", label: "Mongolian" },
  { code: "npi", label: "Nepali" },
  { code: "nor", label: "Norwegian" },
  { code: "oci", label: "Occitan" },
  { code: "ori", label: "Odia" },
  { code: "pus", label: "Pashto" },
  { code: "fas", label: "Persian" },
  { code: "pol", label: "Polish" },
  { code: "por", label: "Portuguese" },
  { code: "pan", label: "Punjabi" },
  { code: "ron", label: "Romanian" },
  { code: "rus", label: "Russian" },
  { code: "srp", label: "Serbian" },
  { code: "sna", label: "Shona" },
  { code: "snd", label: "Sindhi" },
  { code: "sin", label: "Sinhala" },
  { code: "slk", label: "Slovak" },
  { code: "slv", label: "Slovenian" },
  { code: "som", label: "Somali" },
  { code: "spa", label: "Spanish" },
  { code: "sun", label: "Sundanese" },
  { code: "swa", label: "Swahili" },
  { code: "swe", label: "Swedish" },
  { code: "tgk", label: "Tajik" },
  { code: "tam", label: "Tamil" },
  { code: "tat", label: "Tatar" },
  { code: "tel", label: "Telugu" },
  { code: "tha", label: "Thai" },
  { code: "bod", label: "Tibetan" },
  { code: "tur", label: "Turkish" },
  { code: "tuk", label: "Turkmen" },
  { code: "ukr", label: "Ukrainian" },
  { code: "urd", label: "Urdu" },
  { code: "uig", label: "Uyghur" },
  { code: "uzb", label: "Uzbek" },
  { code: "vie", label: "Vietnamese" },
  { code: "cym", label: "Welsh" },
  { code: "xho", label: "Xhosa" },
  { code: "yid", label: "Yiddish" },
  { code: "yor", label: "Yoruba" },
  { code: "zul", label: "Zulu" },
];

// Quick lookup by code
export const SCRIBE_LANGUAGE_MAP: Record<string, string> = Object.fromEntries(
  SCRIBE_LANGUAGES.map((l) => [l.code, l.label])
);
